const USER_DATA_REQUEST = 'user/REQUEST';
const USER_DATA_SUCCESS = 'user/REQUEST_SUCCESS';
const USER_DATA_ERROR = 'user/REQUEST_ERROR';
const USER_DATA_UPDATE_REQUEST = 'user/UPDATE_REQUEST';
const USER_DATA_UPDATE_SUCCESS = 'user/UPDATE_SUCCESS';
const USER_DATA_UPDATE_ERROR = 'user/UPDATE_ERROR';

export default {
  USER_DATA_REQUEST,
  USER_DATA_SUCCESS,
  USER_DATA_ERROR,
  USER_DATA_UPDATE_REQUEST,
  USER_DATA_UPDATE_SUCCESS,
  USER_DATA_UPDATE_ERROR,
};
